name    'opencsw'
version '0.1.0'
source 'https://github.com/juliengk/puppet-module-opencsw'
author 'Julien K'
license 'Apache License, Version 2.0'
summary 'Manage OpenCSW pkgutil on Solaris 10 systems'
description 'Puppet module for installing and managing OpenCSW pkgutil'
project_page 'https://github.com/juliengk/puppet-module-opencsw'
